#!/bin/bash
#TODO Rewrite in python
# ---- Notepad For Bash ---- #
# ----   By: Lucidity   ---- #
source config.sh
#Check if note directory exists, if not create it
if [[ ! -d $noteDir ]]
    then
	$firstRun = 1;
	echo "Begining Setup ..."
	echo ""
	echo "Create Program Directory"
	echo ""
	mkdir $noteDir
	echo "$noteDir Created"
	echo ""
fi
###################################################
#		    Build UI			  #
#                                                 #
#                                                 #
#                                                 #
###################################################
echo "    Welcome to nPad - A notepad for bash"
echo "   Developed By Developers For Developers"
echo ""
echo "#############################################"
echo "#            | Selection Menu |             #"
echo "#-------------------------------------------#"
echo "#                                           #"
echo "# n -Start A New Note                       #"
echo "# o -Open A Previous Note                   #"
echo "# l -List Note Files                        #"
echo "# v -View Configuration File                #"
echo "#                                           #"
echo "# -->To run without ui start with -s        #"
echo "#-------------------------------------------#"
echo "#          | Enter Your Selection |         #"
echo "#############################################"
echo ""
read $menuSelection

if [[ ! -e $todaysNote ]]
then
    touch $todaysNote
	if [[ -e $todaysNote ]]
	    then
    	    echo "Created Note File $todaysNote"
		newFile=1
	    else "Error Unable To Create Note"
	fi
else newFile=0
fi

#Add Note Header To New File

if [[ $newFile = 1 ]]
    then
	echo "################################" >> $todaysNote
	echo "# "$(date)" #" >> $todaysNote
	echo "################################" >> $todaysNote

#Add New Entry Tab
    
    else
	 nowTime=`date +%H:%M`
	echo "Title"
	echo ""
	read entryName
	echo "" >> $todaysNote
	echo "################################" >> $todaysNote
	echo "$nowTime $entryName          " >> $todaysNote
	echo "################################" >> $todaysNote

fi

#Add while read line loop to take user input 
	echo "Enter notes followed by [ CTRl+D ]"	
	while read line
   	do
	echo "$line" >> $todaysNote
	done

exit
